// --- Full organizationData ---
export const organizationData = {
  id: "1",
  name: "Timothy Jones",
  position: "DevOps Engineer",
  department: "Engineering",
  email: "TimothyJones@gmail.com",
  imageUrl:
    "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  expanded: true,
  children: [
    {
      id: "2",
      name: "Sarah Johnson",
      position: "HR Director",
      department: "People & HR",
      email: "sarahjohnson@gmail.com",
      imageUrl:
        "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      expanded: false,
      children: [
        {
          id: "6",
          name: "Mike Wilson",
          position: "HR Manager",
          department: "People & HR",
          email: "mikewilson@gmail.com",
          imageUrl:
            "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          expanded: false,
          children: [
            {
              id: "9",
              name: "Emma Davis",
              position: "HR Specialist",
              department: "People & HR",
              email: "emmadavis@gmail.com",
              imageUrl:
                "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            },
            {
              id: "220",
              name: "William Bonilla",
              position: "Talent Acquisition Specialist",
              department: "People & HR",
              email: "williambonilla@gmail.com",
              imageUrl: "",
            },
            {
              id: "1002",
              name: "Heather Hendricks",
              position: "Talent Acquisition Specialist",
              department: "People & HR",
              email: "heatherhendricks@gmail.com",
              imageUrl: "",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      name: "Robert Smith",
      position: "Head of Engineering",
      department: "Engineering",
      email: "robertsmith@gmail.com",
      imageUrl:
        "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      expanded: false,
      children: [
        {
          id: "2001",
          name: "Codex Engineer Bot",
          position: "AI Coding Assistant",
          department: "Engineering",
          email: "codexengineerbot@gmail.com",
          imageUrl: "",
        },
        {
          id: "101",
          name: "AutoInfra Manager",
          position: "Infrastructure AI",
          department: "Engineering",
          email: "autoinframanager@gmail.com",
          imageUrl: "",
        },
        {
          id: "2003",
          name: "Debug AI Assistant",
          position: "Debugging AI",
          department: "Engineering",
          email: "debugaiassistant@gmail.com",
          imageUrl: "",
        },
        {
          id: "7",
          name: "Jennifer Lee",
          position: "Team Lead - Frontend",
          department: "Engineering",
          email: "jenniferlee@gmail.com",
          imageUrl:
            "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          expanded: false,
          children: [
            {
              id: "10",
              name: "Alex Turner",
              position: "Frontend Developer",
              department: "Engineering",
              email: "alexturner@gmail.com",
              imageUrl:
                "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            },
            {
              id: "3001",
              name: "Julia Wilson",
              position: "Frontend Developer",
              department: "Engineering",
              email: "juliawilson@gmail.com",
              imageUrl: "",
            },
            {
              id: "3002",
              name: "Jeffery Fischer",
              position: "Frontend Developer",
              department: "Engineering",
              email: "jefferyfischer@gmail.com",
              imageUrl: "",
            },
            {
              id: "3003",
              name: "Bryan Logan",
              position: "Frontend Developer",
              department: "Engineering",
              email: "bryanlogan@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "3004",
          name: "Seth Michael",
          position: "Backend Developer",
          department: "Engineering",
          email: "sethmichael@gmail.com",
          imageUrl: "",
          children: [
            {
              id: "3005",
              name: "Christina Phillips",
              position: "Backend Developer",
              department: "Engineering",
              email: "christinaphillips@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "3006",
          name: "Timothy Jones",
          position: "DevOps Engineer",
          department: "Engineering",
          email: "timothyjones@gmail.com",
          imageUrl: "",
        },
        {
          id: "3007",
          name: "Kaylee Trevino",
          position: "Software Engineer",
          department: "Engineering",
          email: "kayleetrevino@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "4",
      name: "Emily Brown",
      position: "Head of Marketing",
      department: "Marketing",
      email: "emilybrown@gmail.com",
      imageUrl:
        "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      expanded: false,
      children: [
        {
          id: "4001",
          name: "ContentGPT",
          position: "Content Generation AI",
          department: "Marketing",
          email: "contentgpt@gmail.com",
          imageUrl: "",
        },
        {
          id: "4002",
          name: "AdOptimizer AI",
          position: "Ad Performance AI",
          department: "Marketing",
          email: "adoptimizerai@gmail.com",
          imageUrl: "",
        },
        {
          id: "4003",
          name: "Social Pulse Bot",
          position: "Social Media AI",
          department: "Marketing",
          email: "socialpulsebot@gmail.com",
          imageUrl: "",
        },
        {
          id: "8",
          name: "David Garcia",
          position: "Team Lead - Content",
          department: "Marketing",
          email: "davidgarcia@gmail.com",
          imageUrl:
            "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
          expanded: false,
          children: [
            {
              id: "11",
              name: "Sophia Martinez",
              position: "Content Creator",
              department: "Marketing",
              email: "sophiamartinez@gmail.com",
              imageUrl:
                "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            },
            {
              id: "4004",
              name: "Nancy Parks",
              position: "Content Strategist",
              department: "Marketing",
              email: "nancyparks@gmail.com",
              imageUrl: "",
            },
            {
              id: "4005",
              name: "Sara Hoffman",
              position: "Content Strategist",
              department: "Marketing",
              email: "sarahoffman@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "4006",
          name: "Antonio Stanton",
          position: "Product Marketing Manager",
          department: "Marketing",
          email: "antoniostanton@gmail.com",
          imageUrl: "",
        },
        {
          id: "4007",
          name: "Eric Banks",
          position: "SEO Specialist",
          department: "Marketing",
          email: "ericbanks@gmail.com",
          imageUrl: "",
          children: [
            {
              id: "4008",
              name: "Amanda Peterson",
              position: "SEO Specialist",
              department: "Marketing",
              email: "amandapeterson@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "4009",
          name: "Jonathan Howell",
          position: "Performance Marketer",
          department: "Marketing",
          email: "jonathanhowell@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "5",
      name: "Michael Johnson",
      position: "Head of Finance",
      department: "Finance & Ops",
      email: "michaeljohnson@gmail.com",
      imageUrl:
        "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      expanded: false,
      children: [
        {
          id: "5001",
          name: "Diana Greer",
          position: "Revenue Operations Manager",
          department: "Finance & Ops",
          email: "dianagreer@gmail.com",
          imageUrl: "",
        },
        {
          id: "5002",
          name: "Nicole Baker",
          position: "FP&A Analyst",
          department: "Finance & Ops",
          email: "nicolebaker@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "6001",
      name: "Mark Alexander",
      position: "Head of Product",
      department: "Product",
      email: "markalexander@gmail.com",
      imageUrl: "",
      expanded: false,
      children: [
        {
          id: "6002",
          name: "Voice of Customer AI",
          position: "Customer Insights AI",
          department: "Product",
          email: "voiceofcustomerai@gmail.com",
          imageUrl: "",
        },
        {
          id: "6003",
          name: "Roadmap Companion",
          position: "Product Planning AI",
          department: "Product",
          email: "roadmapcompanion@gmail.com",
          imageUrl: "",
        },
        {
          id: "6004",
          name: "Usage Analytics Bot",
          position: "Product Analytics AI",
          department: "Product",
          email: "usageanalyticsbot@gmail.com",
          imageUrl: "",
        },
        {
          id: "6005",
          name: "Breanna Smith",
          position: "Product Manager",
          department: "Product",
          email: "breannasmith@gmail.com",
          imageUrl: "",
          children: [
            {
              id: "6006",
              name: "Christopher Esparza",
              position: "Associate Product Manager",
              department: "Product",
              email: "christopheresparza@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "6007",
          name: "Olivia Gomez",
          position: "Product Manager",
          department: "Product",
          email: "oliviagomez@gmail.com",
          imageUrl: "",
          children: [
            {
              id: "6008",
              name: "Tyler Peters",
              position: "Associate Product Manager",
              department: "Product",
              email: "tylerpeters@gmail.com",
              imageUrl: "",
            },
          ],
        },
        {
          id: "6009",
          name: "Connie Decker",
          position: "Product Analyst",
          department: "Product",
          email: "conniedecker@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "7001",
      name: "Sara John",
      position: "Head of Design",
      department: "Design",
      email: "sarajohn@gmail.com",
      imageUrl: "",
      expanded: false,
      children: [
        {
          id: "7002",
          name: "Larry Warner",
          position: "UI Designer",
          department: "Design",
          email: "larrywarner@gmail.com",
          imageUrl: "",
        },
        {
          id: "7003",
          name: "Paul Wright",
          position: "UI Designer",
          department: "Design",
          email: "paulwright@gmail.com",
          imageUrl: "",
        },
        {
          id: "7004",
          name: "Kenneth Brown",
          position: "UX Designer",
          department: "Design",
          email: "kennethbrown@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "8001",
      name: "Jean Gray",
      position: "Head of Customer Success",
      department: "Customer Success",
      email: "jeangray@gmail.com",
      imageUrl: "",
      expanded: false,
      children: [
        {
          id: "8002",
          name: "Edward Hernandez",
          position: "Customer Success Manager",
          department: "Customer Success",
          email: "edwardhernandez@gmail.com",
          imageUrl: "",
        },
        {
          id: "8003",
          name: "Steven Pierce",
          position: "Customer Success Manager",
          department: "Customer Success",
          email: "stevenpierce@gmail.com",
          imageUrl: "",
        },
        {
          id: "8004",
          name: "Don Forbes",
          position: "Customer Success Manager",
          department: "Customer Success",
          email: "donforbes@gmail.com",
          imageUrl: "",
        },
      ],
    },
    {
      id: "9001",
      name: "Ace  Sawyer",
      position: "Head of Sales",
      department: "Sales",
      email: "acesawyer@gmail.com",
      imageUrl: "",
      expanded: false,
      children: [
        {
          id: "9002",
          name: "Edward Simpson",
          position: "Sales Development Rep",
          department: "Sales",
          email: "edwardsimpson@gmail.com",
          imageUrl: "",
        },
        {
          id: "9003",
          name: "Jessica Peterson",
          position: "Account Executive",
          department: "Sales",
          email: "jessicapeterson@gmail.com",
          imageUrl: "",
        },
      ],
    },
  ],
};